Don't fail easily when wikipedia.py version cannot be determined
My script fails with:

Traceback (most recent call last):
  File "eksport.py", line 4, in <module>
    import wikipedia
  File "/home/admini/saper/wikipedia/pywikipedia/wikipedia.py", line 8748, in <module>
    writeToCommandLogFile()
  File "/home/admini/saper/wikipedia/pywikipedia/wikipedia.py", line 8685, in writeToCommandLogFile
    % (isoDate, version.getversiondict()['rev'],
  File "/home/admini/saper/wikipedia/pywikipedia/pywikibot/version.py", line 43, in getversiondict
    if len(version) == 4:
TypeError: object of type 'NoneType' has no len()


The reason is that my scripts reach pywikipedia via sys.path 
and are not located in the pywikipedia directory.

This fixes the len(version) == 4 case, since version
can be returned None.

A proper fix to determine wikipedia.py is needed, maybe.


git-svn-id: http://svn.wikimedia.org/svnroot/pywikipedia/trunk/pywikipedia@10917 6a7f98fc-eeb0-4dc1-a6e2-c2c589a08aa6